# Generated by Django 5.1.2 on 2025-11-22 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranscriptionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading Chunks"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("original_filename", models.CharField(max_length=255)),
                ("gcs_uri", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.BigIntegerField()),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("total_chunks", models.IntegerField(default=1)),
                ("chunks_uploaded", models.IntegerField(default=0)),
                ("chunks_processed", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="transcripti_status_94147a_idx",
                    ),
                    models.Index(fields=["email"], name="transcripti_email_bef071_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranscriptionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_transcription", models.TextField()),
                ("processed_transcription", models.TextField()),
                ("word_count", models.IntegerField()),
                ("confidence_score", models.FloatField()),
                ("speakers_detected", models.IntegerField(default=0)),
                ("processing_time_seconds", models.FloatField()),
                ("langchain_metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="transcription.transcriptiontask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gcs_uri", models.CharField(blank=True, max_length=500)),
                ("start_time_ms", models.IntegerField()),
                ("end_time_ms", models.IntegerField()),
                ("duration_ms", models.IntegerField()),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("raw_transcription", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("speakers_detected", models.IntegerField(default=0)),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="transcription.transcriptiontask",
                    ),
                ),
            ],
            options={
                "ordering": ["task", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["task", "status"], name="transcripti_task_id_40d76f_idx"
                    )
                ],
                "unique_together": {("task", "chunk_index")},
            },
        ),
    ]
